// Generated by gencpp from file hw_interface_plugin_dynamixel/groupServoUpdate.msg
// DO NOT EDIT!


#ifndef HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_GROUPSERVOUPDATE_H
#define HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_GROUPSERVOUPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hw_interface_plugin_dynamixel/servoUpdate.h>

namespace hw_interface_plugin_dynamixel
{
template <class ContainerAllocator>
struct groupServoUpdate_
{
  typedef groupServoUpdate_<ContainerAllocator> Type;

  groupServoUpdate_()
    : updateVector()  {
    }
  groupServoUpdate_(const ContainerAllocator& _alloc)
    : updateVector(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >::other >  _updateVector_type;
  _updateVector_type updateVector;





  typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct groupServoUpdate_

typedef ::hw_interface_plugin_dynamixel::groupServoUpdate_<std::allocator<void> > groupServoUpdate;

typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::groupServoUpdate > groupServoUpdatePtr;
typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::groupServoUpdate const> groupServoUpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hw_interface_plugin_dynamixel

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'hw_interface_plugin_dynamixel': ['/home/derekroesch/catkin_ws/Compilable Mercury Mar26/src/hw_interface_plugins/hw_interface_plugin_dynamixel/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c43f3e284762815cccc83296eda5168d";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc43f3e284762815cULL;
  static const uint64_t static_value2 = 0xccc83296eda5168dULL;
};

template<class ContainerAllocator>
struct DataType< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw_interface_plugin_dynamixel/groupServoUpdate";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servoUpdate[] updateVector\n\
\n\
================================================================================\n\
MSG: hw_interface_plugin_dynamixel/servoUpdate\n\
uint64 ABILITY_NOP = 0\n\
uint64 ABILITY_ANGLE_UNITS=1\n\
uint64 ABILITY_SPEED_UNITS=2\n\
uint64 ABILITY_RESOLUTION_DIVIDER=4\n\
uint64 ABILITY_WHEEL_MODE=8\n\
uint64 ABILITY_JOINT_MODE=16\n\
uint64 ABILITY_CCW_LIMIT=32\n\
uint64 ABILITY_CW_LIMIT=64\n\
uint64 ABILITY_INIT=128\n\
uint64 ABILITY_MOVING_SPEED=256\n\
uint64 ABILITY_GOAL_POSITION=512\n\
uint64 ABILITY_PRESENT_SPEED=1024\n\
uint64 ABILITY_PRESENT_POSITION=2048\n\
uint64 ABILITY_STATUS_RETURN_LEVEL=4096\n\
uint64 ABILITY_OPERATING_MODE=8192\n\
uint64 ABILITY_TORQUE=16384\n\
uint64 ABILITY_PRESENT_CURRENT=32768\n\
uint64 ABILITY_TORQUE_LIMIT=65536\n\
uint64 ABILITY_GOAL_TORQUE=131072\n\
uint8  MODE_NOP=0\n\
uint8  MODE_GET=1\n\
uint8  MODE_SET=2\n\
uint8  MODE_QUERY=4\n\
\n\
\n\
\n\
uint8   id\n\
uint64  abilityRequested\n\
uint8   mode\n\
\n\
bool    isDataSigned\n\
\n\
uint32  uDATA\n\
int32   sDATA\n\
\n\
";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.updateVector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct groupServoUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw_interface_plugin_dynamixel::groupServoUpdate_<ContainerAllocator>& v)
  {
    s << indent << "updateVector[]" << std::endl;
    for (size_t i = 0; i < v.updateVector.size(); ++i)
    {
      s << indent << "  updateVector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >::stream(s, indent + "    ", v.updateVector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_GROUPSERVOUPDATE_H
