// Generated by gencpp from file hw_interface_plugin_dynamixel/servoUpdate.msg
// DO NOT EDIT!


#ifndef HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_SERVOUPDATE_H
#define HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_SERVOUPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw_interface_plugin_dynamixel
{
template <class ContainerAllocator>
struct servoUpdate_
{
  typedef servoUpdate_<ContainerAllocator> Type;

  servoUpdate_()
    : id(0)
    , abilityRequested(0)
    , mode(0)
    , isDataSigned(false)
    , uDATA(0)
    , sDATA(0)  {
    }
  servoUpdate_(const ContainerAllocator& _alloc)
    : id(0)
    , abilityRequested(0)
    , mode(0)
    , isDataSigned(false)
    , uDATA(0)
    , sDATA(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint64_t _abilityRequested_type;
  _abilityRequested_type abilityRequested;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _isDataSigned_type;
  _isDataSigned_type isDataSigned;

   typedef uint32_t _uDATA_type;
  _uDATA_type uDATA;

   typedef int32_t _sDATA_type;
  _sDATA_type sDATA;



  enum {
    ABILITY_NOP = 0u,
    ABILITY_ANGLE_UNITS = 1u,
    ABILITY_SPEED_UNITS = 2u,
    ABILITY_RESOLUTION_DIVIDER = 4u,
    ABILITY_WHEEL_MODE = 8u,
    ABILITY_JOINT_MODE = 16u,
    ABILITY_CCW_LIMIT = 32u,
    ABILITY_CW_LIMIT = 64u,
    ABILITY_INIT = 128u,
    ABILITY_MOVING_SPEED = 256u,
    ABILITY_GOAL_POSITION = 512u,
    ABILITY_PRESENT_SPEED = 1024u,
    ABILITY_PRESENT_POSITION = 2048u,
    ABILITY_STATUS_RETURN_LEVEL = 4096u,
    ABILITY_OPERATING_MODE = 8192u,
    ABILITY_TORQUE = 16384u,
    ABILITY_PRESENT_CURRENT = 32768u,
    ABILITY_TORQUE_LIMIT = 65536u,
    ABILITY_GOAL_TORQUE = 131072u,
    MODE_NOP = 0u,
    MODE_GET = 1u,
    MODE_SET = 2u,
    MODE_QUERY = 4u,
  };


  typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct servoUpdate_

typedef ::hw_interface_plugin_dynamixel::servoUpdate_<std::allocator<void> > servoUpdate;

typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::servoUpdate > servoUpdatePtr;
typedef boost::shared_ptr< ::hw_interface_plugin_dynamixel::servoUpdate const> servoUpdateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hw_interface_plugin_dynamixel

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'hw_interface_plugin_dynamixel': ['/home/derekroesch/catkin_ws/Compilable Mercury Mar26/src/hw_interface_plugins/hw_interface_plugin_dynamixel/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aec93516bd00d77b6c5579d881a6bf44";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaec93516bd00d77bULL;
  static const uint64_t static_value2 = 0x6c5579d881a6bf44ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw_interface_plugin_dynamixel/servoUpdate";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 ABILITY_NOP = 0\n\
uint64 ABILITY_ANGLE_UNITS=1\n\
uint64 ABILITY_SPEED_UNITS=2\n\
uint64 ABILITY_RESOLUTION_DIVIDER=4\n\
uint64 ABILITY_WHEEL_MODE=8\n\
uint64 ABILITY_JOINT_MODE=16\n\
uint64 ABILITY_CCW_LIMIT=32\n\
uint64 ABILITY_CW_LIMIT=64\n\
uint64 ABILITY_INIT=128\n\
uint64 ABILITY_MOVING_SPEED=256\n\
uint64 ABILITY_GOAL_POSITION=512\n\
uint64 ABILITY_PRESENT_SPEED=1024\n\
uint64 ABILITY_PRESENT_POSITION=2048\n\
uint64 ABILITY_STATUS_RETURN_LEVEL=4096\n\
uint64 ABILITY_OPERATING_MODE=8192\n\
uint64 ABILITY_TORQUE=16384\n\
uint64 ABILITY_PRESENT_CURRENT=32768\n\
uint64 ABILITY_TORQUE_LIMIT=65536\n\
uint64 ABILITY_GOAL_TORQUE=131072\n\
uint8  MODE_NOP=0\n\
uint8  MODE_GET=1\n\
uint8  MODE_SET=2\n\
uint8  MODE_QUERY=4\n\
\n\
\n\
\n\
uint8   id\n\
uint64  abilityRequested\n\
uint8   mode\n\
\n\
bool    isDataSigned\n\
\n\
uint32  uDATA\n\
int32   sDATA\n\
\n\
";
  }

  static const char* value(const ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.abilityRequested);
      stream.next(m.mode);
      stream.next(m.isDataSigned);
      stream.next(m.uDATA);
      stream.next(m.sDATA);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servoUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw_interface_plugin_dynamixel::servoUpdate_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "abilityRequested: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.abilityRequested);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "isDataSigned: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isDataSigned);
    s << indent << "uDATA: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.uDATA);
    s << indent << "sDATA: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sDATA);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW_INTERFACE_PLUGIN_DYNAMIXEL_MESSAGE_SERVOUPDATE_H
