// Generated by gencpp from file hw_interface_plugin_agent/LOS.msg
// DO NOT EDIT!


#ifndef HW_INTERFACE_PLUGIN_AGENT_MESSAGE_LOS_H
#define HW_INTERFACE_PLUGIN_AGENT_MESSAGE_LOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw_interface_plugin_agent
{
template <class ContainerAllocator>
struct LOS_
{
  typedef LOS_<ContainerAllocator> Type;

  LOS_()
    : LOS(0)  {
    }
  LOS_(const ContainerAllocator& _alloc)
    : LOS(0)  {
  (void)_alloc;
    }



   typedef uint8_t _LOS_type;
  _LOS_type LOS;





  typedef boost::shared_ptr< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> const> ConstPtr;

}; // struct LOS_

typedef ::hw_interface_plugin_agent::LOS_<std::allocator<void> > LOS;

typedef boost::shared_ptr< ::hw_interface_plugin_agent::LOS > LOSPtr;
typedef boost::shared_ptr< ::hw_interface_plugin_agent::LOS const> LOSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw_interface_plugin_agent::LOS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hw_interface_plugin_agent

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hw_interface_plugin_agent': ['/home/derekroesch/catkin_ws/src/hw_interface_plugins/hw_interface_plugin_agent/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e0c4070d76fb968c478473a13650bdd";
  }

  static const char* value(const ::hw_interface_plugin_agent::LOS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e0c4070d76fb968ULL;
  static const uint64_t static_value2 = 0xc478473a13650bddULL;
};

template<class ContainerAllocator>
struct DataType< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw_interface_plugin_agent/LOS";
  }

  static const char* value(const ::hw_interface_plugin_agent::LOS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LOS\n\
";
  }

  static const char* value(const ::hw_interface_plugin_agent::LOS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LOS);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LOS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw_interface_plugin_agent::LOS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw_interface_plugin_agent::LOS_<ContainerAllocator>& v)
  {
    s << indent << "LOS: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LOS);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW_INTERFACE_PLUGIN_AGENT_MESSAGE_LOS_H
