(cl:in-package msgs_and_srvs-msg)
(cl:export '(POINTINSIDEBUMPER-VAL
          POINTINSIDEBUMPER
          CLOSESTPOINTDISTANCE-VAL
          CLOSESTPOINTDISTANCE
          CLOSESTPOINTDIRECTION-VAL
          CLOSESTPOINTDIRECTION
))