(cl:defpackage msgs_and_srvs-msg
  (:use )
  (:export
   "<ARMMANUALMODE>"
   "ARMMANUALMODE"
   "<DRIVECOMMANDS>"
   "DRIVECOMMANDS"
   "<DRIVEVECTOR>"
   "DRIVEVECTOR"
   "<NAVSTATES>"
   "NAVSTATES"
   "<SERVOCOMMANDS>"
   "SERVOCOMMANDS"
   "<SERVOFEEDBACK>"
   "SERVOFEEDBACK"
   "<VIRTUALBUMPERPARAMS>"
   "VIRTUALBUMPERPARAMS"
   "<VIRTUALBUMPERSTATUS>"
   "VIRTUALBUMPERSTATUS"
   "<WEBCAMCOMMANDS>"
   "WEBCAMCOMMANDS"
  ))

