# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msgs_and_srvs/ServoFeedback.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ServoFeedback(genpy.Message):
  _md5sum = "ad381411873b60f8ac0ce1b85ac7dbd2"
  _type = "msgs_and_srvs/ServoFeedback"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 flSpeed
float32 blSpeed
float32 frSpeed
float32 brSpeed
float32 flTurnAngle
float32 blTurnAngle
float32 frTurnAngle
float32 brTurnAngle
"""
  __slots__ = ['flSpeed','blSpeed','frSpeed','brSpeed','flTurnAngle','blTurnAngle','frTurnAngle','brTurnAngle']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flSpeed,blSpeed,frSpeed,brSpeed,flTurnAngle,blTurnAngle,frTurnAngle,brTurnAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoFeedback, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.flSpeed is None:
        self.flSpeed = 0.
      if self.blSpeed is None:
        self.blSpeed = 0.
      if self.frSpeed is None:
        self.frSpeed = 0.
      if self.brSpeed is None:
        self.brSpeed = 0.
      if self.flTurnAngle is None:
        self.flTurnAngle = 0.
      if self.blTurnAngle is None:
        self.blTurnAngle = 0.
      if self.frTurnAngle is None:
        self.frTurnAngle = 0.
      if self.brTurnAngle is None:
        self.brTurnAngle = 0.
    else:
      self.flSpeed = 0.
      self.blSpeed = 0.
      self.frSpeed = 0.
      self.brSpeed = 0.
      self.flTurnAngle = 0.
      self.blTurnAngle = 0.
      self.frTurnAngle = 0.
      self.brTurnAngle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.flSpeed, _x.blSpeed, _x.frSpeed, _x.brSpeed, _x.flTurnAngle, _x.blTurnAngle, _x.frTurnAngle, _x.brTurnAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.flSpeed, _x.blSpeed, _x.frSpeed, _x.brSpeed, _x.flTurnAngle, _x.blTurnAngle, _x.frTurnAngle, _x.brTurnAngle,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.flSpeed, _x.blSpeed, _x.frSpeed, _x.brSpeed, _x.flTurnAngle, _x.blTurnAngle, _x.frTurnAngle, _x.brTurnAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.flSpeed, _x.blSpeed, _x.frSpeed, _x.brSpeed, _x.flTurnAngle, _x.blTurnAngle, _x.frTurnAngle, _x.brTurnAngle,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
