// Generated by gencpp from file msgs_and_srvs/VirtualBumperParams.msg
// DO NOT EDIT!


#ifndef MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERPARAMS_H
#define MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgs_and_srvs
{
template <class ContainerAllocator>
struct VirtualBumperParams_
{
  typedef VirtualBumperParams_<ContainerAllocator> Type;

  VirtualBumperParams_()
    : active(false)
    , radius(0.0)
    , springConstant(0.0)  {
    }
  VirtualBumperParams_(const ContainerAllocator& _alloc)
    : active(false)
    , radius(0.0)
    , springConstant(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _springConstant_type;
  _springConstant_type springConstant;





  typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualBumperParams_

typedef ::msgs_and_srvs::VirtualBumperParams_<std::allocator<void> > VirtualBumperParams;

typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperParams > VirtualBumperParamsPtr;
typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperParams const> VirtualBumperParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msgs_and_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msgs_and_srvs': ['/home/derekroesch/catkin_ws/Compilable Mercury Mar26/src/msgs_and_srvs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f390f4d392b83cae602d14c4638fb17";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f390f4d392b83caULL;
  static const uint64_t static_value2 = 0xe602d14c4638fb17ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_and_srvs/VirtualBumperParams";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool active\n\
float32 radius\n\
float32 springConstant\n\
";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
      stream.next(m.radius);
      stream.next(m.springConstant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualBumperParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_and_srvs::VirtualBumperParams_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "springConstant: ";
    Printer<float>::stream(s, indent + "  ", v.springConstant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERPARAMS_H
