# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hw_interface_plugin_dynamixel/servoStateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class servoStateResponse(genpy.Message):
  _md5sum = "9c96febecb04b5e21700ffa78c48387a"
  _type = "hw_interface_plugin_dynamixel/servoStateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 ABILITY_NOP = 0
uint64 ABILITY_ANGLE_UNITS=1
uint64 ABILITY_SPEED_UNITS=2
uint64 ABILITY_RESOLUTION_DIVIDER=4
uint64 ABILITY_WHEEL_MODE=8
uint64 ABILITY_JOINT_MODE=16
uint64 ABILITY_CCW_LIMIT=32
uint64 ABILITY_CW_LIMIT=64
uint64 ABILITY_INIT=128
uint64 ABILITY_MOVING_SPEED=256
uint64 ABILITY_GOAL_POSITION=512
uint64 ABILITY_PRESENT_SPEED=1024
uint64 ABILITY_PRESENT_POSITION=2048
uint64 ABILITY_STATUS_RETURN_LEVEL=4096
uint8  MODE_NOP=0
uint8  MODE_GET=1
uint8  MODE_SET=2
uint8  MODE_QUERY=4

uint8   id
uint64  queryAbility

uint32  uDATA
int32  sDATA
"""
  # Pseudo-constants
  ABILITY_NOP = 0
  ABILITY_ANGLE_UNITS = 1
  ABILITY_SPEED_UNITS = 2
  ABILITY_RESOLUTION_DIVIDER = 4
  ABILITY_WHEEL_MODE = 8
  ABILITY_JOINT_MODE = 16
  ABILITY_CCW_LIMIT = 32
  ABILITY_CW_LIMIT = 64
  ABILITY_INIT = 128
  ABILITY_MOVING_SPEED = 256
  ABILITY_GOAL_POSITION = 512
  ABILITY_PRESENT_SPEED = 1024
  ABILITY_PRESENT_POSITION = 2048
  ABILITY_STATUS_RETURN_LEVEL = 4096
  MODE_NOP = 0
  MODE_GET = 1
  MODE_SET = 2
  MODE_QUERY = 4

  __slots__ = ['id','queryAbility','uDATA','sDATA']
  _slot_types = ['uint8','uint64','uint32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,queryAbility,uDATA,sDATA

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(servoStateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.queryAbility is None:
        self.queryAbility = 0
      if self.uDATA is None:
        self.uDATA = 0
      if self.sDATA is None:
        self.sDATA = 0
    else:
      self.id = 0
      self.queryAbility = 0
      self.uDATA = 0
      self.sDATA = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BQIi().pack(_x.id, _x.queryAbility, _x.uDATA, _x.sDATA))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.id, _x.queryAbility, _x.uDATA, _x.sDATA,) = _get_struct_BQIi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BQIi().pack(_x.id, _x.queryAbility, _x.uDATA, _x.sDATA))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.id, _x.queryAbility, _x.uDATA, _x.sDATA,) = _get_struct_BQIi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BQIi = None
def _get_struct_BQIi():
    global _struct_BQIi
    if _struct_BQIi is None:
        _struct_BQIi = struct.Struct("<BQIi")
    return _struct_BQIi
