// Generated by gencpp from file msgs_and_srvs/ArmManualMode.msg
// DO NOT EDIT!


#ifndef MSGS_AND_SRVS_MESSAGE_ARMMANUALMODE_H
#define MSGS_AND_SRVS_MESSAGE_ARMMANUALMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgs_and_srvs
{
template <class ContainerAllocator>
struct ArmManualMode_
{
  typedef ArmManualMode_<ContainerAllocator> Type;

  ArmManualMode_()
    : manualMode(false)
    , selectedJoint()  {
    }
  ArmManualMode_(const ContainerAllocator& _alloc)
    : manualMode(false)
    , selectedJoint(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _manualMode_type;
  _manualMode_type manualMode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _selectedJoint_type;
  _selectedJoint_type selectedJoint;





  typedef boost::shared_ptr< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> const> ConstPtr;

}; // struct ArmManualMode_

typedef ::msgs_and_srvs::ArmManualMode_<std::allocator<void> > ArmManualMode;

typedef boost::shared_ptr< ::msgs_and_srvs::ArmManualMode > ArmManualModePtr;
typedef boost::shared_ptr< ::msgs_and_srvs::ArmManualMode const> ArmManualModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msgs_and_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'msgs_and_srvs': ['/home/derekroesch/catkin_ws/src/msgs_and_srvs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e2c37a64ce17164b802f9f6014495cb";
  }

  static const char* value(const ::msgs_and_srvs::ArmManualMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e2c37a64ce17164ULL;
  static const uint64_t static_value2 = 0xb802f9f6014495cbULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_and_srvs/ArmManualMode";
  }

  static const char* value(const ::msgs_and_srvs::ArmManualMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool manualMode\n\
string selectedJoint\n\
";
  }

  static const char* value(const ::msgs_and_srvs::ArmManualMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.manualMode);
      stream.next(m.selectedJoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmManualMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_and_srvs::ArmManualMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_and_srvs::ArmManualMode_<ContainerAllocator>& v)
  {
    s << indent << "manualMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manualMode);
    s << indent << "selectedJoint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.selectedJoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_AND_SRVS_MESSAGE_ARMMANUALMODE_H
