// Generated by gencpp from file msgs_and_srvs/VirtualBumperStatus.msg
// DO NOT EDIT!


#ifndef MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERSTATUS_H
#define MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgs_and_srvs
{
template <class ContainerAllocator>
struct VirtualBumperStatus_
{
  typedef VirtualBumperStatus_<ContainerAllocator> Type;

  VirtualBumperStatus_()
    : pointInsideBumper(false)
    , closestPointDistance(0.0)
    , closestPointDirection(0.0)  {
    }
  VirtualBumperStatus_(const ContainerAllocator& _alloc)
    : pointInsideBumper(false)
    , closestPointDistance(0.0)
    , closestPointDirection(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _pointInsideBumper_type;
  _pointInsideBumper_type pointInsideBumper;

   typedef float _closestPointDistance_type;
  _closestPointDistance_type closestPointDistance;

   typedef float _closestPointDirection_type;
  _closestPointDirection_type closestPointDirection;





  typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualBumperStatus_

typedef ::msgs_and_srvs::VirtualBumperStatus_<std::allocator<void> > VirtualBumperStatus;

typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperStatus > VirtualBumperStatusPtr;
typedef boost::shared_ptr< ::msgs_and_srvs::VirtualBumperStatus const> VirtualBumperStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msgs_and_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msgs_and_srvs': ['/home/derekroesch/catkin_ws/src/msgs_and_srvs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04d921a3fed1e194d4292fdcb5f3f0a3";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04d921a3fed1e194ULL;
  static const uint64_t static_value2 = 0xd4292fdcb5f3f0a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_and_srvs/VirtualBumperStatus";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool pointInsideBumper\n\
float32 closestPointDistance\n\
float32 closestPointDirection\n\
";
  }

  static const char* value(const ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointInsideBumper);
      stream.next(m.closestPointDistance);
      stream.next(m.closestPointDirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualBumperStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_and_srvs::VirtualBumperStatus_<ContainerAllocator>& v)
  {
    s << indent << "pointInsideBumper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pointInsideBumper);
    s << indent << "closestPointDistance: ";
    Printer<float>::stream(s, indent + "  ", v.closestPointDistance);
    s << indent << "closestPointDirection: ";
    Printer<float>::stream(s, indent + "  ", v.closestPointDirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_AND_SRVS_MESSAGE_VIRTUALBUMPERSTATUS_H
